---
language: python
services: docker

arch:
  - amd64
  - arm64

before_install:
  - docker build -t frankjoshua/ros-master .

script:
  - docker images frankjoshua/ros-master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push frankjoshua/ros-master;
    fi
