---
language: python
services: docker

env:
  - DOCKER_CONTAINER=frankjoshua/ros-master

before_install:
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    ./build.sh $DOCKER_CONTAINER --push;
