---
dist: xenial
sudo: required
services: docker

env:
  global:
    - DOCKER_CONTAINER=frankjoshua/ros-master

before_install:
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

script:
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo ./build.sh $DOCKER_CONTAINER --push;
