---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

env:
  DOCKER_CONTAINER: frankjoshua/ros-master
  AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-16.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
