---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

env:
  DOCKER_CONTAINER: frankjoshua/ros-master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-16.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to DockerHub
        uses: actions/checkout@v2
        run: ./build.sh -t $DOCKER_CONTAINER -q -p
